builds:
  - binary: haproxy-gen
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
  files:
    - sample-config.yml
    - haproxy.cfg.tmpl

changelog:
  filters:
    exclude:
      - '^build:'
      - '^tweak:'
