language: go

sudo: required

services:
  - docker

go:
- '1.7'

cache:
  directories:
    - vendor

install:
  - go get github.com/mitchellh/gox
  - go get github.com/Masterminds/glide
  - glide install

script:
  - go test $(glide novendor)

after_success:
  - gox
        -osarch "linux/386 linux/amd64 darwin/amd64"
        -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}"
  - docker run --rm -v $(pwd):/go/src/github.com/itzg/haproxy-gen
      -w /go/src/github.com/itzg/haproxy-gen
      -e SKIP_GLIDE=1 itzg/go-alpine-build:1.7 dist/haproxy-gen_alpine
  - "sudo chown ${USER}: dist/*"
  - cd dist ; for f in *; do tar zcvf $f.tgz $f; done; cd -
  - ls -l dist

deploy:
  provider: releases
  api_key: "${GITHUB_API_KEY}"
  file:
    - dist/haproxy-gen_linux_386.tgz
    - dist/haproxy-gen_linux_amd64.tgz
    - dist/haproxy-gen_darwin_amd64.tgz
    - dist/haproxy-gen_alpine.tgz
  skip_cleanup: true
  on:
    tags: true
