templatepath: .
certs: /etc/certs

frontendstats:
  enabled: true
  basepath: /ft_stats
  user: superuser
  password: simple

domains:
- domain: one.example.com
  servers:
  - server1:8080
  userlistname: u1
  stats:
    enabled: true
    basepath: /stats
    user: admin
    password: admin
- domain: two.example.com
  servers:
  - server2:8080
  - server3:8080

userlists:
- userlist: u1
  users:
  - username: admin
    encpassword: $1$B7LfUIdP$PQGZFB2JQ0Tq/BRQrCtG//
  - username: copilot
    encpassword: $1$4U5Xcs62$HHa2WkdRfgFO3g9s/H8SV0
- userlist: u2
  users:
  - username: bonus
    encpassword: $1$8K.gBKHa$/lmmOPZi5uTugyGkLvi/Z1

extra:
  global: "#end of global"
  defaults: "#end of defaults"
  end: "#end of the end"
  frontend: "#end of the frontend"
  prefrontend: "#start of the frontend"
